export type ColorThemeId =
  | "classic"
  | "ocean"
  | "forest"
  | "sunset"
  | "slate"
  | "coral"
  | "indigo"
  | "mint"
  | "rose"
  | "amber"
  | "wine"
  | "sky";

export type ColorTheme = {
  id: ColorThemeId;
  label: string;
  /** CSS custom properties applied to the page root */
  vars: Record<string, string>;
  /** Hex values for charts / canvas that need concrete colors */
  chart: {
    invested: string;
    gain: string;
    tax: string;
  };
};

export const COLOR_THEMES: ColorTheme[] = [
  {
    id: "classic",
    label: "Classic",
    vars: {
      "--app-bg": "#faf9f6",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(248, 250, 252, 0.6)",
      "--app-border": "#e2e8f0",
      "--app-text": "#0f172a",
      "--app-text-muted": "#64748b",
      "--app-text-subtle": "#94a3b8",
      "--app-primary": "#0f172a",
      "--app-primary-hover": "#1e293b",
      "--app-primary-soft": "#64748b",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#cbd5e1",
      "--app-std-bg": "#e0f2fe",
      "--app-std-bg-soft": "rgba(224, 242, 254, 0.6)",
      "--app-std-text": "#075985",
      "--app-std-text-strong": "#082f49",
      "--app-step-bg": "#d1fae5",
      "--app-step-bg-soft": "rgba(209, 250, 229, 0.6)",
      "--app-step-text": "#065f46",
      "--app-step-text-strong": "#022c22",
      "--app-warn-bg": "#fffbeb",
      "--app-warn-border": "#fde68a",
      "--app-warn-text": "#92400e",
      "--app-warn-text-strong": "#451a03",
      "--app-warn-muted": "#b45309",
      "--app-danger": "#ef4444",
      "--app-bar-track": "#f8fafc",
    },
    chart: {
      invested: "#152033",
      gain: "#34d399",
      tax: "#f87171",
    },
  },
  {
    id: "ocean",
    label: "Ocean",
    vars: {
      "--app-bg": "#f0f9ff",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(224, 242, 254, 0.55)",
      "--app-border": "#bae6fd",
      "--app-text": "#0c4a6e",
      "--app-text-muted": "#0369a1",
      "--app-text-subtle": "#7dd3fc",
      "--app-primary": "#0369a1",
      "--app-primary-hover": "#075985",
      "--app-primary-soft": "#38bdf8",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#e0f2fe",
      "--app-std-bg": "#cffafe",
      "--app-std-bg-soft": "rgba(207, 250, 254, 0.6)",
      "--app-std-text": "#0e7490",
      "--app-std-text-strong": "#164e63",
      "--app-step-bg": "#ccfbf1",
      "--app-step-bg-soft": "rgba(204, 251, 241, 0.6)",
      "--app-step-text": "#0f766e",
      "--app-step-text-strong": "#134e4a",
      "--app-warn-bg": "#ecfeff",
      "--app-warn-border": "#a5f3fc",
      "--app-warn-text": "#155e75",
      "--app-warn-text-strong": "#083344",
      "--app-warn-muted": "#0e7490",
      "--app-danger": "#e11d48",
      "--app-bar-track": "#e0f2fe",
    },
    chart: {
      invested: "#0c4a6e",
      gain: "#2dd4bf",
      tax: "#fb7185",
    },
  },
  {
    id: "forest",
    label: "Forest",
    vars: {
      "--app-bg": "#f7faf7",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(236, 253, 245, 0.55)",
      "--app-border": "#d1e7dd",
      "--app-text": "#14532d",
      "--app-text-muted": "#3f6212",
      "--app-text-subtle": "#86efac",
      "--app-primary": "#166534",
      "--app-primary-hover": "#14532d",
      "--app-primary-soft": "#4ade80",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#dcfce7",
      "--app-std-bg": "#dcfce7",
      "--app-std-bg-soft": "rgba(220, 252, 231, 0.6)",
      "--app-std-text": "#166534",
      "--app-std-text-strong": "#052e16",
      "--app-step-bg": "#ecfccb",
      "--app-step-bg-soft": "rgba(236, 252, 203, 0.6)",
      "--app-step-text": "#3f6212",
      "--app-step-text-strong": "#1a2e05",
      "--app-warn-bg": "#fef9c3",
      "--app-warn-border": "#fde047",
      "--app-warn-text": "#854d0e",
      "--app-warn-text-strong": "#422006",
      "--app-warn-muted": "#a16207",
      "--app-danger": "#dc2626",
      "--app-bar-track": "#f0fdf4",
    },
    chart: {
      invested: "#14532d",
      gain: "#4ade80",
      tax: "#f87171",
    },
  },
  {
    id: "sunset",
    label: "Sunset",
    vars: {
      "--app-bg": "#fff7ed",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(255, 237, 213, 0.55)",
      "--app-border": "#fed7aa",
      "--app-text": "#7c2d12",
      "--app-text-muted": "#9a3412",
      "--app-text-subtle": "#fdba74",
      "--app-primary": "#c2410c",
      "--app-primary-hover": "#9a3412",
      "--app-primary-soft": "#fb923c",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#ffedd5",
      "--app-std-bg": "#ffedd5",
      "--app-std-bg-soft": "rgba(255, 237, 213, 0.65)",
      "--app-std-text": "#9a3412",
      "--app-std-text-strong": "#7c2d12",
      "--app-step-bg": "#fecdd3",
      "--app-step-bg-soft": "rgba(254, 205, 211, 0.6)",
      "--app-step-text": "#9f1239",
      "--app-step-text-strong": "#4c0519",
      "--app-warn-bg": "#fef3c7",
      "--app-warn-border": "#fcd34d",
      "--app-warn-text": "#92400e",
      "--app-warn-text-strong": "#451a03",
      "--app-warn-muted": "#b45309",
      "--app-danger": "#e11d48",
      "--app-bar-track": "#fff7ed",
    },
    chart: {
      invested: "#9a3412",
      gain: "#fb923c",
      tax: "#fb7185",
    },
  },
  {
    id: "slate",
    label: "Slate",
    vars: {
      "--app-bg": "#f1f5f9",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(241, 245, 249, 0.7)",
      "--app-border": "#cbd5e1",
      "--app-text": "#0f172a",
      "--app-text-muted": "#475569",
      "--app-text-subtle": "#94a3b8",
      "--app-primary": "#334155",
      "--app-primary-hover": "#1e293b",
      "--app-primary-soft": "#64748b",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#e2e8f0",
      "--app-std-bg": "#e2e8f0",
      "--app-std-bg-soft": "rgba(226, 232, 240, 0.65)",
      "--app-std-text": "#334155",
      "--app-std-text-strong": "#0f172a",
      "--app-step-bg": "#dbeafe",
      "--app-step-bg-soft": "rgba(219, 234, 254, 0.6)",
      "--app-step-text": "#1e40af",
      "--app-step-text-strong": "#172554",
      "--app-warn-bg": "#f8fafc",
      "--app-warn-border": "#cbd5e1",
      "--app-warn-text": "#475569",
      "--app-warn-text-strong": "#0f172a",
      "--app-warn-muted": "#64748b",
      "--app-danger": "#dc2626",
      "--app-bar-track": "#f8fafc",
    },
    chart: {
      invested: "#1e293b",
      gain: "#60a5fa",
      tax: "#f87171",
    },
  },
  {
    id: "coral",
    label: "Coral",
    vars: {
      "--app-bg": "#fff5f3",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(255, 237, 233, 0.6)",
      "--app-border": "#fecaca",
      "--app-text": "#7f1d1d",
      "--app-text-muted": "#b91c1c",
      "--app-text-subtle": "#fca5a5",
      "--app-primary": "#e11d48",
      "--app-primary-hover": "#be123c",
      "--app-primary-soft": "#fb7185",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#ffe4e6",
      "--app-std-bg": "#fee2e2",
      "--app-std-bg-soft": "rgba(254, 226, 226, 0.65)",
      "--app-std-text": "#b91c1c",
      "--app-std-text-strong": "#7f1d1d",
      "--app-step-bg": "#ffedd5",
      "--app-step-bg-soft": "rgba(255, 237, 213, 0.65)",
      "--app-step-text": "#c2410c",
      "--app-step-text-strong": "#7c2d12",
      "--app-warn-bg": "#fff7ed",
      "--app-warn-border": "#fdba74",
      "--app-warn-text": "#9a3412",
      "--app-warn-text-strong": "#7c2d12",
      "--app-warn-muted": "#ea580c",
      "--app-danger": "#dc2626",
      "--app-bar-track": "#fff1f2",
    },
    chart: {
      invested: "#9f1239",
      gain: "#fb923c",
      tax: "#f43f5e",
    },
  },
  {
    id: "indigo",
    label: "Indigo",
    vars: {
      "--app-bg": "#f5f3ff",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(237, 233, 254, 0.55)",
      "--app-border": "#c4b5fd",
      "--app-text": "#312e81",
      "--app-text-muted": "#4338ca",
      "--app-text-subtle": "#a5b4fc",
      "--app-primary": "#4338ca",
      "--app-primary-hover": "#3730a3",
      "--app-primary-soft": "#818cf8",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#e0e7ff",
      "--app-std-bg": "#e0e7ff",
      "--app-std-bg-soft": "rgba(224, 231, 255, 0.65)",
      "--app-std-text": "#3730a3",
      "--app-std-text-strong": "#1e1b4b",
      "--app-step-bg": "#f3e8ff",
      "--app-step-bg-soft": "rgba(243, 232, 255, 0.65)",
      "--app-step-text": "#7e22ce",
      "--app-step-text-strong": "#4a044e",
      "--app-warn-bg": "#faf5ff",
      "--app-warn-border": "#d8b4fe",
      "--app-warn-text": "#6b21a8",
      "--app-warn-text-strong": "#3b0764",
      "--app-warn-muted": "#7e22ce",
      "--app-danger": "#e11d48",
      "--app-bar-track": "#eef2ff",
    },
    chart: {
      invested: "#312e81",
      gain: "#a78bfa",
      tax: "#fb7185",
    },
  },
  {
    id: "mint",
    label: "Mint",
    vars: {
      "--app-bg": "#f0fdfa",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(204, 251, 241, 0.5)",
      "--app-border": "#99f6e4",
      "--app-text": "#134e4a",
      "--app-text-muted": "#0f766e",
      "--app-text-subtle": "#5eead4",
      "--app-primary": "#0d9488",
      "--app-primary-hover": "#0f766e",
      "--app-primary-soft": "#2dd4bf",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#ccfbf1",
      "--app-std-bg": "#ccfbf1",
      "--app-std-bg-soft": "rgba(204, 251, 241, 0.65)",
      "--app-std-text": "#0f766e",
      "--app-std-text-strong": "#134e4a",
      "--app-step-bg": "#d1fae5",
      "--app-step-bg-soft": "rgba(209, 250, 229, 0.65)",
      "--app-step-text": "#047857",
      "--app-step-text-strong": "#064e3b",
      "--app-warn-bg": "#ecfdf5",
      "--app-warn-border": "#6ee7b7",
      "--app-warn-text": "#065f46",
      "--app-warn-text-strong": "#022c22",
      "--app-warn-muted": "#059669",
      "--app-danger": "#e11d48",
      "--app-bar-track": "#f0fdfa",
    },
    chart: {
      invested: "#134e4a",
      gain: "#2dd4bf",
      tax: "#fb7185",
    },
  },
  {
    id: "rose",
    label: "Rose",
    vars: {
      "--app-bg": "#fff1f2",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(255, 228, 230, 0.55)",
      "--app-border": "#fecdd3",
      "--app-text": "#881337",
      "--app-text-muted": "#be123c",
      "--app-text-subtle": "#fda4af",
      "--app-primary": "#e11d48",
      "--app-primary-hover": "#be123c",
      "--app-primary-soft": "#fb7185",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#ffe4e6",
      "--app-std-bg": "#fce7f3",
      "--app-std-bg-soft": "rgba(252, 231, 243, 0.65)",
      "--app-std-text": "#9d174d",
      "--app-std-text-strong": "#500724",
      "--app-step-bg": "#f3e8ff",
      "--app-step-bg-soft": "rgba(243, 232, 255, 0.65)",
      "--app-step-text": "#7e22ce",
      "--app-step-text-strong": "#4a044e",
      "--app-warn-bg": "#fdf2f8",
      "--app-warn-border": "#f9a8d4",
      "--app-warn-text": "#9d174d",
      "--app-warn-text-strong": "#500724",
      "--app-warn-muted": "#db2777",
      "--app-danger": "#dc2626",
      "--app-bar-track": "#fff1f2",
    },
    chart: {
      invested: "#881337",
      gain: "#f472b6",
      tax: "#f43f5e",
    },
  },
  {
    id: "amber",
    label: "Amber",
    vars: {
      "--app-bg": "#fffbeb",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(254, 243, 199, 0.55)",
      "--app-border": "#fde68a",
      "--app-text": "#78350f",
      "--app-text-muted": "#92400e",
      "--app-text-subtle": "#fbbf24",
      "--app-primary": "#d97706",
      "--app-primary-hover": "#b45309",
      "--app-primary-soft": "#f59e0b",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#fef3c7",
      "--app-std-bg": "#fef3c7",
      "--app-std-bg-soft": "rgba(254, 243, 199, 0.65)",
      "--app-std-text": "#b45309",
      "--app-std-text-strong": "#78350f",
      "--app-step-bg": "#ffedd5",
      "--app-step-bg-soft": "rgba(255, 237, 213, 0.65)",
      "--app-step-text": "#c2410c",
      "--app-step-text-strong": "#7c2d12",
      "--app-warn-bg": "#fefce8",
      "--app-warn-border": "#facc15",
      "--app-warn-text": "#854d0e",
      "--app-warn-text-strong": "#422006",
      "--app-warn-muted": "#ca8a04",
      "--app-danger": "#dc2626",
      "--app-bar-track": "#fffbeb",
    },
    chart: {
      invested: "#92400e",
      gain: "#fbbf24",
      tax: "#f87171",
    },
  },
  {
    id: "wine",
    label: "Wine",
    vars: {
      "--app-bg": "#faf5f5",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(254, 226, 226, 0.4)",
      "--app-border": "#e7d3d3",
      "--app-text": "#4c0519",
      "--app-text-muted": "#881337",
      "--app-text-subtle": "#c4a4a4",
      "--app-primary": "#9f1239",
      "--app-primary-hover": "#881337",
      "--app-primary-soft": "#be123c",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#fecdd3",
      "--app-std-bg": "#f5e6e8",
      "--app-std-bg-soft": "rgba(245, 230, 232, 0.7)",
      "--app-std-text": "#9f1239",
      "--app-std-text-strong": "#4c0519",
      "--app-step-bg": "#ede9fe",
      "--app-step-bg-soft": "rgba(237, 233, 254, 0.65)",
      "--app-step-text": "#5b21b6",
      "--app-step-text-strong": "#2e1065",
      "--app-warn-bg": "#fdf2f8",
      "--app-warn-border": "#f9a8d4",
      "--app-warn-text": "#9f1239",
      "--app-warn-text-strong": "#4c0519",
      "--app-warn-muted": "#be123c",
      "--app-danger": "#b91c1c",
      "--app-bar-track": "#faf5f5",
    },
    chart: {
      invested: "#4c0519",
      gain: "#c084fc",
      tax: "#f43f5e",
    },
  },
  {
    id: "sky",
    label: "Sky",
    vars: {
      "--app-bg": "#f0f9ff",
      "--app-surface": "#ffffff",
      "--app-surface-muted": "rgba(224, 242, 254, 0.5)",
      "--app-border": "#7dd3fc",
      "--app-text": "#0c4a6e",
      "--app-text-muted": "#0284c7",
      "--app-text-subtle": "#38bdf8",
      "--app-primary": "#0284c7",
      "--app-primary-hover": "#0369a1",
      "--app-primary-soft": "#38bdf8",
      "--app-primary-fg": "#ffffff",
      "--app-primary-fg-muted": "#e0f2fe",
      "--app-std-bg": "#e0f2fe",
      "--app-std-bg-soft": "rgba(224, 242, 254, 0.7)",
      "--app-std-text": "#0369a1",
      "--app-std-text-strong": "#0c4a6e",
      "--app-step-bg": "#dbeafe",
      "--app-step-bg-soft": "rgba(219, 234, 254, 0.7)",
      "--app-step-text": "#1d4ed8",
      "--app-step-text-strong": "#1e3a8a",
      "--app-warn-bg": "#eff6ff",
      "--app-warn-border": "#93c5fd",
      "--app-warn-text": "#1e40af",
      "--app-warn-text-strong": "#1e3a8a",
      "--app-warn-muted": "#2563eb",
      "--app-danger": "#e11d48",
      "--app-bar-track": "#f0f9ff",
    },
    chart: {
      invested: "#0c4a6e",
      gain: "#38bdf8",
      tax: "#fb7185",
    },
  },
];

export function getColorTheme(id: ColorThemeId): ColorTheme {
  return COLOR_THEMES.find((t) => t.id === id) ?? COLOR_THEMES[0];
}
